name: Daily ArXiv to Discord

on:
  schedule:
    # 한국시간 평일 오전 7시 = UTC 전날 22시
    # cron은 UTC 기준이므로 월-금 22시에 실행하면 
    # 한국시간으로 화-토 오전 7시에 실행됨
    - cron: '0 22 * * 1-5'  # 월-금 22시 UTC (화-토 7시 KST)
  workflow_dispatch:

jobs:
  post-arxiv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          WEBHOOK_2D: ${{ secrets.WEBHOOK_2D }}
          WEBHOOK_3D: ${{ secrets.WEBHOOK_3D }}
        run: python arxiv_to_discord.py
