name: Daily ArXiv to Discord

on:
  schedule:
    - cron: '0 22 * * *'  # 한국시간 오전 7시
  workflow_dispatch:

jobs:
  post-arxiv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          WEBHOOK_2D: ${{ secrets.WEBHOOK_2D }}
          WEBHOOK_3D: ${{ secrets.WEBHOOK_3D }}
        run: python arxiv_to_discord.py
